version: '3.8'

services:
  database:
    image: postgres
    container_name: database_services
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=database_env
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: database_app
    restart: always
    ports:
      - 5050:5050
    volumes:
      - .:/usr/app
    links:
      - database

volumes:
  pgdata:
      driver: local